services:
  auth:
    container_name: auth-service
    build: ./auth-service
    image: auth-service
    restart: always
    env_file:
      - ./auth-service/.env
    networks:
      - back-end
    ports:
      - "3000:3000"
  
  profile:
    container_name: profile-service
    build: ./profile-service
    image: profile-service
    restart: always
    env_file:
      - ./profile-service/.env
    networks:
      - back-end
    ports:
      - "3001:3001"
networks:
  back-end:
    name: backend
    driver: bridge