services:
  auth:
    container_name: auth-service
    build: ./auth-service
    image: auth-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  profile:
    container_name: profile-service
    build: ./profile-service
    image: profile-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy

  friends:
    container_name: friends-service
    build: ./friends-service
    image: friends-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy

  notifications:
    container_name: notifications-service
    build: ./notifications-service
    image: notifications-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  back-end:
    name: backend
    driver: bridge
