services:
  auth:
    container_name: auth-service
    build: ./auth-service
    image: auth-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3000:3000"
  
  profile:
    container_name: profile-service
    build: ./profile-service
    image: profile-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3001:3001"

  friends:
    container_name: friends-service
    build: ./friends-service
    image: friends-service
    restart: always
    env_file:
      - .env
    networks:
      - back-end
    ports:
      - "3002:3002"

      
networks:
  back-end:
    name: backend
    driver: bridge