services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
